[project]
name = "whisper-app"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["faster-whisper>=1.1.1", "flet[all]>=0.28.3", "rich>=14.0.0"]

[tool.taskipy.tasks]
start = "python app/main.py"
